from time import sleep
import webbrowser
import pyautogui
import pyperclip

minimizar=pyautogui.moveTo(1248,10)
sleep(3)
#com o VS code em tela cheia , minimiza o VS code aberto , com o navegagador em tela cheia de fundo
pyautogui.click()
webbrowser.open('https://instragam.com')
sleep(20)
# 20 segundos de espera para carregar a pagina em meu caso
# Em meu navegador notifca que ja registrei uma conta no instagram
# 20 segundos de espera para carregar a pagina em meu caso
acessar_outra_conta=pyautogui.moveTo(930,579)
sleep(2)
pyautogui.click()
sleep(2)
pyautogui.moveTo(856,304)
sleep(2)
pyautogui.click()
pyperclip.copy('DIGITE SEU NOME DE USUARIO')
pyautogui.move(856,304)
pyautogui.click()
pyautogui.hotkey('ctrl', 'v')
pyautogui.moveTo(840,345)
sleep(2)
pyautogui.click()
pyperclip.copy('DIGITE SUA SENHA ')
pyautogui.move(840,345)
pyautogui.click()
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.doubleClick(837,268)
sleep(10)
pyautogui.moveTo(786,498)
sleep(4)
pyautogui.moveTo(786,498)
sleep(2)
pyautogui.doubleClick()
sleep(18)
pyautogui.moveTo(97,302)
pyautogui.click()
sleep(5)
pyautogui.moveTo(186,213)
pyautogui.doubleClick()
pyperclip.copy('neymarjr')
pyautogui.click()
pyautogui.hotkey('ctrl', 'v')
pyautogui.moveTo(171,293)
sleep(5)
pyautogui.click()
sleep(8)
pyautogui.moveTo(550,403)
sleep(3)
pyautogui.scroll(-200)
sleep(5)
pyautogui.moveTo(442,744)
sleep(5)
pyautogui.click()
curtir = pyautogui.moveTo(764,595)
sleep(3)
pyautogui.click()
sleep(2)